### Category - Create Category
POST http://localhost:3001/api/categories
Content-Type: application/json

{
  "name": "Food and Drinks",
  "description": "Semua Makanan dan Minuman",
  "createdBy": 5
}

### Category - Get All Categories
GET http://localhost:3001/api/categories

### Menampilkan Ringkasan per Kategori
GET http://localhost:3001/api/items/summary/category