### Item - Create Item
POST http://localhost:3001/api/items
Content-Type: application/json

{
  "name": "dragon fruit tree",
  "description": "Dari Kebun Tetangga",
  "price": 10.99,
  "quantity": 1,
  "categoryId": 2,
  "supplierId": 4,
  "createdBy": 3
}

### Item - Get All Items
GET http://localhost:3001/api/items

### Item - Get Low-Stock Items (Threshold below 5 units)
GET http://localhost:3001/api/items/low-stock

### Item - Get Items by Specific Category (category yg saya buat hanya 1-4)
GET http://localhost:3001/api/items/category/4 

### Stock Summary - Displays total stock, value, and average price
GET http://localhost:3001/api/items/summary/stock

### System Summary - Overview of Total Items, Categories, Suppliers, and Stock Value
GET http://localhost:3001/api/items/summary/system
