services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: hakem
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    ports:
      - "3001:3000"
    depends_on:
      - database
    
  prisma:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: ["npx", "prisma", "studio"]
    ports:
      - "5555:5555"
    depends_on:
      - database

volumes:
  postgres_data: